### ISSUE TITLE
question: request/prepare

### ISSUE THREAD

**Issue by jimmont** [mhingston/tedious-wrapper#1]
When using tedious-wrapper what's the optimal way to setup a request where the application will be making the same request repeatedly (with varying values)?

In my particular case an express app provides parameter values via `request.query` like `{name1:value1}`. I was using `connection.prepare(request)` prior to using tedious-wrapper and in looking at the README thought to ask (for an opinion/example).

Thanks.

**Comment by mhingston** [comment]
Hi @jimmont,

tedious-wrapper doesn't wrap the prepare/unprepare methods of tedious currently. If you need to use the native methods of the tedious connection object I would just use the [tedious API](http://tediousjs.github.io/tedious/api-connection.html) once you've acquired a connection i.e. after `db.connect` which returns a connection object.

    // Callback
    db.connect((error, connection) =>
    {
        connection.prepare(...)
    });

    // Promise
    db.connect()
    .then((connection) =>
    {
        connection.prepare(...)
    })
    .catch((error) =>
    {
        // your code goes here
    });

    // Async/await
    async function connect()
    {
        let connection;

        try
        {
            connection = await db.connect();
            connection.prepare(...)
        }

        catch(error)
        {
            // your code goes here
        }
    };

Otherwise you can mimic the prepare method using the following code (although this won't ensure that all requests are processed by the same connection):

    const myRequest =
    {
        sql: 'SELECT FirstName, LastName, EmailAddress FROM [User] WHERE UserID = @UserID',
        parameters:
        [
            ['UserID', db.types.Int, 1]
        ],
        callback: (error, resultSets) =>
        {
            // your code goes here
        }
    }

    // Callback
    db.request(Object.assign(myRequest,
    {
        parameters:
        [
            ['UserID', db.types.Int, 2]
        ]
    }));

    // Promise
    db.request(Object.assign(myRequest,
    {
        parameters:
        [
            ['UserID', db.types.Int, 2]
        ]
    }))
    .then((resultSets) =>
    {
        
    })
    .catch((error) =>
    {

    });

    // Async/await
    async function request()
    {
        let resultSets;

        try
        {
            resultSets = await db.request(Object.assign(myRequest,
            {
                parameters:
                [
                    ['UserID', db.types.Int, 2]
                ]
            }));
        }

        catch(error)
        {

        }
    };

**Comment by jimmont** [comment]
thanks very much @mhingston 👍🏾this is super helpful
